use_frameworks!

target 'FYUploader_Example' do
  pod 'FYUploader', :path => '../'
  pod 'ZLPhotoBrowser'
  pod 'FrameAccessor'

  target 'FYUploader_Tests' do
    inherit! :search_paths

    
  end
end
